
/*
 * Assumption/integration test.
 */
verb:get
url:"/magic/modules/system/auth/authenticate?username=root&password=not-a-valid-password"
status:int:401
response:@"{""message"":""Access denied"",""stack-trace"":""   at magic.lambda.exceptions.Throw.Signal(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/exceptions/Throw.cs:line 34\n   at magic.signals.services.Signaler.SignalAsync(String name, Node input) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 141\n   at magic.lambda.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 85\n   at magic.lambda.Eval.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 40\n   at magic.lambda.branching.Else.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/branching/Else.cs:line 39\n   at magic.lambda.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 85\n   at magic.lambda.Eval.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 40\n   at magic.lambda.mysql.Connect.<>c__DisplayClass3_0.<<SignalAsync>b__0>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.lambda.mysql/magic.lambda.mysql/Connect.cs:line 72\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.lambda.mysql.Connect.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda.mysql/magic.lambda.mysql/Connect.cs:line 69\n   at magic.data.common.slots.Connect.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.data.common/magic.data.common/slots/Connect.cs:line 59\n   at magic.lambda.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 85\n   at magic.lambda.Eval.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 40\n   at magic.lambda.slots.SignalSlot.<>c__DisplayClass1_1.<<SignalAsync>b__1>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.lambda.slots/magic.lambda.slots/Signal.cs:line 62\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.lambda.slots.SignalSlot.<>c__DisplayClass1_0.<<SignalAsync>b__0>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.lambda.slots/magic.lambda.slots/Signal.cs:line 60\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.lambda.slots.SignalSlot.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda.slots/magic.lambda.slots/Signal.cs:line 56\n   at magic.lambda.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 85\n   at magic.lambda.Eval.SignalAsync(ISignaler signaler, Node input) in /Users/thomashansen/Documents/projects/magic/magic.lambda/magic.lambda/Eval.cs:line 40\n   at magic.endpoint.services.ExecutorAsync.<>c__DisplayClass7_0.<<ExecuteUrl>b__2>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.services/ExecutorAsync.cs:line 121\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.endpoint.services.ExecutorAsync.<>c__DisplayClass7_0.<<ExecuteUrl>b__1>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.services/ExecutorAsync.cs:line 119\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.endpoint.services.ExecutorAsync.<>c__DisplayClass7_0.<<ExecuteUrl>b__0>d.MoveNext() in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.services/ExecutorAsync.cs:line 117\n--- End of stack trace from previous location where exception was thrown ---\n   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor) in /Users/thomashansen/Documents/projects/magic/magic.signals/magic.signals.services/Signaler.cs:line 190\n   at magic.endpoint.services.ExecutorAsync.ExecuteUrl(String url, String verb, IEnumerable`1 args, IEnumerable`1 headers, JContainer payload) in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.services/ExecutorAsync.cs:line 115\n   at magic.endpoint.services.ExecutorAsync.ExecuteGetAsync(String url, IEnumerable`1 args, IEnumerable`1 headers) in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.services/ExecutorAsync.cs:line 44\n   at magic.endpoint.controller.EndpointController.Get(String url) in /Users/thomashansen/Documents/projects/magic/magic.endpoint/magic.endpoint/magic.endpoint.controller/EndpointController.cs:line 52\n   at lambda_method(Closure , Object )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)""}"
.description:@"Assumes trying to authenticate with wrong password fails"
